### ISSUE TITLE
Error when Running start.sh script

### ISSUE THREAD

**Issue by danindiana** [BumblebeeBat/MerkleTrie#21]
After installing Erlang for Ubuntu 16.04 and running the start.sh script I get this: 

sudo sh start.sh 
[sudo] password 
==> jiffy (get-deps)
==> encrypter (get-deps)
==> pink_hash (get-deps)
==> dump (get-deps)
==> MerkleTrie-master (get-deps)
==> jiffy (compile)
==> encrypter (compile)
==> pink_hash (compile)
==> dump (compile)
==> MerkleTrie-master (compile)
mkdir: cannot create directory ‘data’: File exists
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> 
=INFO REPORT==== 26-Jan-2018::22:29:16 ===
    application: trie
    exited: {{shutdown,
                 {failed_to_start_child,trie01_leaf,
                     {shutdown,
                         {failed_to_start_child,trie01_leaf_bits,
                             {undef,
                                 [{hipe_bifs,bitarray,[1000000,false],[]},
                                  {bits,init,1,
                                      [{file,"src/bits.erl"},{line,9}]},
                                  {gen_server,init_it,6,
                                      [{file,"gen_server.erl"},{line,328}]},
                                  {proc_lib,init_p_do_apply,3,
                                      [{file,"proc_lib.erl"},
                                       {line,240}]}]}}}}},
             {trie_app,start,[normal,[]]}}
    type: temporary

OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.13.0-31-generic
 Uptime: 2d 8h 31m
 Packages: 2686
 Shell: bash 4.3.48
 Resolution: 2560x1080
 DE: Unity 7.4.0
 WM: Compiz
 WM Theme: Radiance
Radiance [GTK2]
, Radiance [GTK3]
 Icon Theme: ubuntu-mono-light
 Font: Ubuntu 11
 CPU: AMD FX-8350 Eight-Core @ 4GHz
 GPU: GeForce GTX 750 Ti
 RAM: 11219MiB / 24003MiB

**Comment by zack-bitcoin** [comment]
There are 2 problems I see.
1) You should not use sudo to run this software.
2) you need the erlang-hipe dependency. 

Take a look at the amoveo installation instructions.

**Comment by danindiana** [comment]
@zack-bitcoin Thanks! That did the trick. 

https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/linux_dependencies.md

and 

https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/turn_it_on.md

Running on this system: 

OS: Mint 18.1 serena
 Kernel: x86_64 Linux 4.4.0-104-generic
 Uptime: 28m
 Packages: 3289
 Shell: bash 4.3.48
 Resolution: 1920x1080
 DE: Cinnamon 3.2.7
 WM: Muffin
 WM Theme: Linux Mint (Mint-X)
Mint-X [GTK2]
, Mint-X [GTK3]
 Icon Theme: Mint-X
 Font: Noto Sans 9
 CPU: Intel Core i5-6300U CPU @ 3GHz
 GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
 RAM: 2503MiB / 7850MiB
