### ISSUE TITLE
Error and crash dump when running test_trie.erl 

### ISSUE THREAD

**Issue by danindiana** [BumblebeeBat/MerkleTrie#22]
And I fully admit I don't know my way around Erlang CLI in Linux but am willing to learn. 
[erl_crash.txt](https://github.com/BumblebeeBat/MerkleTrie/files/1676180/erl_crash.txt)

MerkleTrie/src$erl -run test_trie.erl 
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

{"init terminating in do_boot",{undef,[{'test_trie.erl',start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

Note I've got amoveo running: 

/amoveo'
Attaching to /tmp/erl_pipes/ae_core_prod@strelkov-ThinkPad-X260/erlang.pipe.1 (^D to exit)

start keys
tx_pool- blockchain ready
starting secrets
start order book 
Eshell V7.3  (abort with ^G)
(ae_core_prod@strelkov-ThinkPad-X260)1> [-7,159,89,106,253]

 OS: Mint 18.1 serena
 Kernel: x86_64 Linux 4.4.0-104-generic
 Uptime: 16m
 Packages: 3289
 Shell: bash 4.3.48
 Resolution: 1920x1080
 DE: Cinnamon 3.2.7
 WM: Muffin
 WM Theme: Linux Mint (Mint-X)
Mint-X [GTK2]
, Mint-X [GTK3]
 Icon Theme: Mint-X
 Font: Noto Sans 9
 CPU: Intel Core i5-6300U CPU @ 3GHz
 GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
 RAM: 2393MiB / 7850MiB

**Comment by zack-bitcoin** [comment]
What is your goal with the MerkleTrie software?
This is a library that I don't expect users to ever have to know about.
It gets installed automatically by Amoveo.

You should be able to run the tests while running the merkle trie by itself without Amoveo.
`test_trie:test().`

I think you cannot run the test from inside Amoveo. Even though Amoveo is using this merkle trie, I think that Amoveo is not loading the test-trie into ram, so you can't run the test which depends on that test-trie.

If you want to help Amoveo, I recommend looking at the Amoveo docs and pointing out which parts are confusing.

**Comment by danindiana** [comment]
Thanks for the input. I will take a look at Amoveo and see what I come up with.
